on: [push, pull_request, workflow_dispatch]
jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install server modules
        working-directory: ./applications/server/
        run: npm ci
      - name: Running tests
        working-directory: ./
        run:
          node --experimental-vm-modules ./applications/server/node_modules/jest/bin/jest.js --coverage --coverageReporters json-summary
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main

# working-directory: applications/server/tests/
